=== calmnature/practice3dspace/resources/resources/param/DELPPWApplications/xsd/ColumnConfigWithHeader.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" targetNamespace="DS_DELPPWConfiguration" xmlns:mstns="DS_DELPPWConfiguration" xmlns="DS_DELPPWConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:element name="Label">
    <xs:complexType>
      <xs:attribute name="dataIndex" form="unqualified" type="xs:string" />
      <xs:attribute name="dicoType" form="unqualified" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="Column">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="dicoType" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="dicoType" form="unqualified" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element ref="Label" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="Column" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="dataIndex" form="unqualified" type="xs:string" />
      <xs:attribute name="minWidth" form="unqualified" type="xs:string" />
      <xs:attribute name="display" form="unqualified" type="xs:string" />
      <xs:attribute name="dicoType" form="unqualified" type="xs:string" />
      <xs:attribute name="displayType" form="unqualified" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Columns" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
	            <xs:element name="Label" minOccurs="0" maxOccurs="unbounded" />
              <xs:element ref="Column" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" form="unqualified" type="xs:string" />
      <xs:attribute name="Title" form="unqualified" type="xs:string" />
      <xs:attribute name="Description" form="unqualified" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="NewDataSet" >
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
	      <xs:element ref="Label" />
        <xs:element ref="Column" />
        <xs:element ref="Config" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== calmnature/practice3dspace/3dspace/webapps/DELWKOApp/assets/xml/RoutingsViewColumnConfigCloud.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config name="Routings" xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/ColumnConfigWithHeader.xsd" Title="UI Config" Description="Sample configuration file delivered by DS.">
   <Columns>
     <Column dataIndex="GeneralInformation.reference" >
     <Label dataIndex="V_Name.reference" dicoType="PLMEntity"/>
       <!-- <Column dataIndex="V_Name.reference" dicoType="PLMEntity"/> -->
     <Column dataIndex="PLM_ExternalID.reference" minWidth="50" display="false"/>
     <Column dataIndex="V_description.reference"  dicoType="PLMEntity" minWidth="50" display="false"/>
     <Column dataIndex="type.reference" minWidth="50" displayType="NonEditable" display="false"/>
     <Column dataIndex="modified.reference" dicoType="BusinessType" display="false"/>
     <!-- <Column dataIndex="created.reference" dicoType="BusinessType" display="false"/> -->
     <Column dataIndex="current.reference" displayType="URL" dicoType="BusinessType"  minWidth="50"/>
     <Column dataIndex="owner.reference" dicoType="BusinessType"  displayType="NonEditableOwner" minWidth="50" display="false"/>
     <Column dataIndex="rejectReason.reference" displayType="NonEditable" minWidth="50" display="true"/>

     <Column dataIndex="orderNo.reference" minWidth="50" display="false"/>

     <Column dataIndex="V_Priority.reference" displayType="PriorityMultiType" minWidth="50" display="true">
             <dicoType dicoType="DELLmiOperationUPRReference" />
             <dicoType dicoType="DELLmiUPRSystemReference" />
     </Column>

     <Column dataIndex="description.reference" dicoType="PLMEntity"  minWidth="150" displayType="NonEditable" display="false"/>
       <Column dataIndex="V_DueDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50"/>

       <!-- <Column dataIndex="V_OrderQuantity.reference" displayType="NonEditable" minWidth="50" display="true"> -->
       <Column dataIndex="V_OrderQuantity.reference" displayType="OrderQtyMultiType" minWidth="50" display="true">
             <dicoType dicoType="DELLmiWOQuantity_Each" />
             <dicoType dicoType="DELLmiWOQuantity_Area" />
             <dicoType dicoType="DELLmiWOQuantity_Length" />
             <dicoType dicoType="DELLmiWOQuantity_Weight" />
              <dicoType dicoType="DELLmiWOQuantity_Volume" />
       </Column>

       <!-- <Column dataIndex="V_CompletedQuantity.reference" dicoType="DELLmiOperationUPRReference"  minWidth="50"/> -->
       <!-- <Column dataIndex="V_CompletedQuantity.reference" displayType="MultiType" minWidth="50" display="true"> -->
        <Column dataIndex="V_CompletedQuantity.reference" displayType="NonEditableQtyMultiType" minWidth="50" display="true">
             <dicoType dicoType="DELLmiEOQuantity_Each" />
             <dicoType dicoType="DELLmiEOQuantity_Area" />
             <dicoType dicoType="DELLmiEOQuantity_Length" />
             <dicoType dicoType="DELLmiEOQuantity_Weight" />
              <dicoType dicoType="DELLmiEOQuantity_Volume" />
       </Column>

       <Column dataIndex="SerializedFrom.relation" displayType="Relation"/>
       <Column dataIndex="MfgProductionPlanning.relation" displayType="Relation"/>
       <Column dataIndex="ProductionPlanReference.relation" displayType="Relation"/>
       <Column dataIndex="AssetContext.relation" displayType="Relation"/>

       <Column dataIndex="Build.relation" displayType="Relation"/>
		<Column dataIndex="SerializedItem.relation" displayType="Relation"/>
     </Column>


     <Column dataIndex="Scheduling.reference" >
       <!-- <Column dataIndex="capacitySchedulingSpace.reference"  minWidth="50" display="false"/> -->
       <Column dataIndex="V_CapacitySchedulingSpace.reference" dicoType="DELLmiAdditionalTime"  minWidth="50" display="false"/>
       <Column dataIndex="V_Scheduled.reference" dicoType="DELLmiOperationUPRReference" display="false"/>
     <Column dataIndex="V_CalculatedDueDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50" display="false"/>
     <Column dataIndex="V_EarliestStartDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50" display="false"/>
     <Column dataIndex="V_GanttColor.reference" dicoType="DELLmiProdSysAndResourceReferenceExt"  displayType="Color"  minWidth="50" display="false"/>
     <!-- <Column dataIndex="V_TargetStartDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50" display="false"/> -->
     <Column dataIndex="V_TargetStartDate.reference" displayType="MultiType" minWidth="50" display="false">
             <dicoType dicoType="DELLmiOperationUPRReference" />
             <dicoType dicoType="DELLmiUPRSystemReference" />
     </Column>

     <!-- <Column dataIndex="V_TargetEndDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50" display="false"/> -->
     <Column dataIndex="V_TargetEndDate.reference" displayType="MultiType" minWidth="50" display="false">
             <dicoType dicoType="DELLmiOperationUPRReference" />
             <dicoType dicoType="DELLmiUPRSystemReference" />
     </Column>

     <!-- <Column dataIndex="V_PlannedStartDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50" display="false"/> -->
     <Column dataIndex="V_PlannedStartDate.reference" displayType="MultiType" minWidth="50" display="false">
             <dicoType dicoType="DELLmiOperationUPRReference" />
             <dicoType dicoType="DELLmiUPRSystemReference" />
     </Column>

     <!-- <Column dataIndex="V_PlannedEndDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50" display="false"/> -->
     <Column dataIndex="V_PlannedEndDate.reference" displayType="MultiType" minWidth="50" display="false">
             <dicoType dicoType="DELLmiOperationUPRReference" />
             <dicoType dicoType="DELLmiUPRSystemReference" />
     </Column>

     <!-- <Column dataIndex="V_ScheduledStartDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50"/> -->
     <Column dataIndex="V_ScheduledStartDate.reference" displayType="MultiType" minWidth="50" display="true">
             <dicoType dicoType="DELLmiOperationUPRReference" />
             <dicoType dicoType="DELLmiUPRSystemReference" />
     </Column>

     <!-- <Column dataIndex="V_ScheduledEndDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50"/> -->
      <Column dataIndex="V_ScheduledEndDate.reference" displayType="MultiType" minWidth="50" display="true">
             <dicoType dicoType="DELLmiOperationUPRReference" />
             <dicoType dicoType="DELLmiUPRSystemReference" />
     </Column>


        <Column dataIndex="V_MinStartDateUser.reference" dicoType="DELLmiMinStartDateUser"  minWidth="50" display="false"/>
        <Column dataIndex="V_DescriptionUser.reference" dicoType="DELLmiMinStartDateUser"  minWidth="50" display="false"/>

        <Column dataIndex="V_MinStartDateAuto.reference" dicoType="DELLmiMinStartDateAuto"  minWidth="50" display="false"/>
        <Column dataIndex="V_DescriptionAuto.reference" dicoType="DELLmiMinStartDateAuto"  minWidth="50" display="false"/>

        <Column dataIndex="V_MinStartDateRawMaterial.reference" dicoType="DELLmiMinStartDateRawMaterial"  minWidth="50" display="false"/>
        <Column dataIndex="V_DescriptionRawMaterial.reference" dicoType="DELLmiMinStartDateRawMaterial"  minWidth="50" display="false"/>

        <Column dataIndex="V_MinStartDateSemiFinished.reference" dicoType="DELLmiMinStartDateSemiFinished"  minWidth="50" display="false"/>
        <Column dataIndex="V_DescriptionSemiFinished.reference" dicoType="DELLmiMinStartDateSemiFinished"  minWidth="50" display="false"/>

     </Column>

     <Column dataIndex="Execution.reference" >
       <Column dataIndex="V_RemainingTime.reference" dicoType="DELLmiOperationUPRReference" minWidth="50" display="false"/>
       <Column dataIndex="V_ActualTime.reference" dicoType="DELLmiOperationUPRReference" minWidth="50" display="false"/>
       <Column dataIndex="onHold.reference" displayType="onHoldType" minWidth="50" display="false"/>
       <Column dataIndex="V_OnHoldComment.reference" dicoType="DELOnHold" minWidth="50" displayType="onHoldComment" display="false"/>

     <!-- <Column dataIndex="V_ActualStartDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50"/> -->
     <Column dataIndex="V_ActualStartDate.reference" displayType="MultiType" minWidth="50">
             <dicoType dicoType="DELLmiOperationUPRReference" />
             <dicoType dicoType="DELLmiUPRSystemReference" />
     </Column>

     <!-- <Column dataIndex="V_ActualEndDate.reference" dicoType="DELLmiUPRSystemReference"  minWidth="50"/> -->
     <Column dataIndex="V_ActualEndDate.reference" displayType="MultiType" minWidth="50">
             <dicoType dicoType="DELLmiOperationUPRReference" />
             <dicoType dicoType="DELLmiUPRSystemReference" />
     </Column>

     <!-- <Column dataIndex="V_InitialQuantity.reference" dicoType="DELLmiOperationUPRReference"  minWidth="50"/> -->
     <!-- <Column dataIndex="V_InitialQuantity.reference" displayType="NonEditable" minWidth="50" display="true">  -->
     <Column dataIndex="V_InitialQuantity.reference" displayType="NonEditableQtyMultiType" minWidth="50" display="true">
          	<dicoType dicoType="DELLmiEOQuantity_Each" />
          	<dicoType dicoType="DELLmiEOQuantity_Area" />
          	<dicoType dicoType="DELLmiEOQuantity_Length" />
          	<dicoType dicoType="DELLmiEOQuantity_Weight" />
            <dicoType dicoType="DELLmiEOQuantity_Volume" />
     </Column>

     <!-- <Column dataIndex="V_RemainingQuantity.reference" dicoType="DELLmiOperationUPRReference"  minWidth="50"/> -->
     <!-- <Column dataIndex="V_RemainingQuantity.reference" displayType="NonEditable" minWidth="50" display="true"> -->
     <Column dataIndex="V_RemainingQuantity.reference" displayType="NonEditableQtyMultiType" minWidth="50" display="true">
