=== calmnature/practice3dspace/3dspace/WEB-INF/resources/DerivedOutput/DerivedFormatDeclarative.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- please do not change a single char in this file without notifying PPN. thnks -->
  
  <xs:complexType name="sourceType">
    <xs:sequence>
      <xs:element type="targetType" name="target" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" 		name="name"		use="required"/>
    <xs:attribute type="sourceTypeType" name="type" 	use="required"/>
    <xs:attribute type="partExtensionType" name="partExtension" use="optional"/> <!-- for eCAD, only applies to 'Part' -->
    <xs:attribute type="subTypeType" 	name="subtype" 	use="optional"/> <!-- for eCAD, only applies to 'Part', but used also for 'Document' -->
   </xs:complexType>
 
<!--  list of possible values for the type attr of a source -->
<xs:simpleType name="sourceTypeType">
  <xs:restriction base="xs:string">
    <!-- Start with the IRPC types of 3DSpace -->
    <xs:enumeration value="Part"/>
    <xs:enumeration value="IPart"/>       <!-- IPART is used by Inventor for Part and iPart -->
    <xs:enumeration value="SEComponent"/> <!-- SEComponent is used by SolidEdge for Part and SheetMetal -->
    <xs:enumeration value="Drawing"/>
    <xs:enumeration value="3DShape"/>
    <xs:enumeration value="SIMShape"/>
	<xs:enumeration value="Material"/>
    <xs:enumeration value="Assembly"/>
    <xs:enumeration value="Analysis"/>
    <xs:enumeration value="Process"/>
    <xs:enumeration value="CREOPart"/>
	<!-- below one matches for CVS Document (ER model) of 3DSpace -->
    <xs:enumeration value="Document"/>
    <!-- Temporary addition for CATIAV5 Converter, should be managed by subType-->
    <xs:enumeration value="CATShape"/>
    <xs:enumeration value="Model"/>
    <xs:enumeration value="cgr"/>
    <!-- For XCADPLMBatch, we start from a private PowerBy Rep
    <xs:enumeration value="XCADNonPSRepReference"/>
    <xs:enumeration value="XCADAssemblyRepReference"/>-->
	<xs:enumeration value="VPMReference"/>
	
 	
  </xs:restriction>
</xs:simpleType>   

<!--  list of possible values for the partExtension attr of a source -->
<xs:simpleType name="partExtensionType">
  <xs:restriction base="xs:string">
    <!-- subtypes of Part for eCAD -->
    <xs:enumeration value="CBDBoard"/>               <!-- Printed Circuit Board -->
    <xs:enumeration value="PLMPCBPackageFootprint"/> <!-- Footprint -->
    <xs:enumeration value="PLMPCBPackageWrap"/>      <!-- PackageWrap -->
 </xs:restriction>
</xs:simpleType>   

 <!--  list of possible values for the subtypes attr of a source -->
<xs:simpleType name="subTypeType">
  <xs:restriction base="xs:string">
    <!-- subtypes of Part for eCAD -->
    <xs:enumeration value="CBDBoard"/>               <!-- Printed Circuit Board -->
    <xs:enumeration value="PLMPCBPackageFootprint"/> <!-- Footprint -->
    <xs:enumeration value="PLMPCBPackageWrap"/>      <!-- PackageWrap -->
   <!-- subtypes of Part for CV5 -->
    <xs:enumeration value="CATShape"/>
    <xs:enumeration value="model"/>
    <xs:enumeration value="cgr"/>
	<!-- subtypes of Document , only Office Doc for now-->
    <xs:enumeration value="config"/>
	<!-- subtypes of Document , only Office Doc for now-->
    <xs:enumeration value="WordProcessed"/>
    <xs:enumeration value="Spreadsheet"/>
    <xs:enumeration value="Presentation"/>
    <xs:enumeration value="email"/>
    <xs:enumeration value="CSV"/>
 	<!-- subtypes of Document , for Image -->
    <xs:enumeration value="raster"/>
    <xs:enumeration value="vectorial"/>
    <xs:enumeration value="AECType"/>
    <!-- New PowerBy model introduced by GEOVIA : original SDM is in a private PowerBy Rep-->
    <xs:enumeration value="XCADNonPSRepReference"/>
    <!--  PowerBy model for CATProduct / assembly xCAD -->
    <xs:enumeration value="XCADAssemblyRepReference"/>
	<!-- Tesselated Part = 3D when authoring stream is cgr -->
    <xs:enumeration value="TesselatedPart"/>      
 </xs:restriction>
</xs:simpleType>   
 
  <xs:complexType name="targetType" mixed="true">
    <xs:sequence>
      <xs:element type="parameterType" name="parameter" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name"           type="xs:string"          use="required" />
	<xs:attribute name="inputStreamId"  type="inputstreamIdType"  use="required" />
    <xs:attribute name="outputStreamId" type="outputstreamIdType" use="required" />
    <xs:attribute name="downloadable"   type="xs:boolean"         use="optional" default="true"/>
    <xs:attribute name="conversionService" type="xs:boolean"      use="optional" default="false"/>
    <xs:attribute name="cloudOnly"      type="xs:boolean"         use="optional" default="false"/>
    <xs:attribute name="onPremiseOnly"  type="xs:boolean"         use="optional" default="false"/>
  </xs:complexType>
  
  <xs:complexType name="parameterType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string"  name="name"		use="required"/>
        <xs:attribute type="xs:string"  name="values"	use="required"/>
        <xs:attribute type="xs:string"  name="type"		use="required"/>
        <xs:attribute type="xs:string"  name="range"	use="optional"/>  <!-- only for int/double/numerical value...not et supported -->
        <xs:attribute type="xs:string"  name="default"	use="optional"/>
        <xs:attribute type="xs:string"  name="description" use="optional"/>
        <xs:attribute type="xs:boolean" name="mandatory" use="optional"/> <!-- default is False if not present -->
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  
<!--  list of possible values for INPUT streamId -->
<xs:simpleType name="inputstreamIdType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="authoring"/>
    <xs:enumeration value="authoringvisu"/>
    <xs:enumeration value="linkable"/>
	<!-- cases with 'DO' prefix means the input in in a stream of DerivedOutputEntity -->
    <xs:enumeration value="DWG"/>
    <xs:enumeration value="DXF"/>
    <xs:enumeration value="STEP"/> <!-- formats may be stp, step, stpZ -->
    <xs:enumeration value="SDM"/> <!-- Geovia Surpac SDM==> new PowerBy model -->
	</xs:restriction>
</xs:simpleType>

<!--  list of possible values for OUTPUT streamId -->
<xs:simpleType name="outputstreamIdType">
  <xs:restriction base="xs:string">
	<!-- first formats for internal DS (not downloadable) -->
	<xs:enumeration value="authoringvisu"/> <!-- CGR, UDL, and ConvService is using 'vizualisation' for 3DXML/UDL -->
	<xs:enumeration value="linkable"/>
	<xs:enumeration value="catiav5"/>
	<xs:enumeration value="XCADPivot"/>
	<xs:enumeration value="acis_powerby"/>
	<xs:enumeration value="visualization"/>
	<!-- and below formats for exchange -->
	<xs:enumeration value="CATPart"/>
	<xs:enumeration value="STEP"/>
	<xs:enumeration value="STEP_AP203"/>
	<xs:enumeration value="STEP_AP214"/>
	<xs:enumeration value="STEP_AP242"/>
	<xs:enumeration value="STEP_Part21"/>
	<xs:enumeration value="PDF"/>
	<xs:enumeration value="PDF/A"/>
	<xs:enumeration value="TIF"/>
	<xs:enumeration value="DWG"/>
	<xs:enumeration value="DWF"/>
	<xs:enumeration value="DXF"/>
	<xs:enumeration value="CGR"/>
	<xs:enumeration value="cgrv5"/>  <!-- light version of catiav5, only tesselation-->
	<xs:enumeration value="HCG"/>
	<xs:enumeration value="MODEL"/>
	<xs:enumeration value="SVG"/>
	<xs:enumeration value="PNG"/>    <!-- PNG includes PNG and BMP, aka lossless raster images -->
	<xs:enumeration value="CGM"/>
	<xs:enumeration value="PS"/>     <!--PostScript-->
	<xs:enumeration value="JPG"/>
	<xs:enumeration value="GIF"/>
	<xs:enumeration value="THUMBNAIL"/>
	<xs:enumeration value="IG2"/>
	<xs:enumeration value="GL2"/>
	<xs:enumeration value="VPS"/>
	<xs:enumeration value="STL"/>
	<xs:enumeration value="IGES"/>
	<xs:enumeration value="WRL"/>
	<xs:enumeration value="3DMAP"/>
	<xs:enumeration value="3DXML"/>
	<xs:enumeration value="CATALOG"/>
	<xs:enumeration value="3DPDF"/>   <!-- proposed by techno/Spatial -->
	<!-- electronic CAD -->
	<xs:enumeration value="IPC2581"/>
	<!-- GEOVIA SURPAC from 23xFD01 -->
	<xs:enumeration value="SurpacSDM"/>
	<xs:enumeration value="OMF"/>
	<!-- XCV from 23xFD01 -->
	<xs:enumeration value="XCV"/>
	<!-- special * value is used when the outputStreamId is computed from mandatory attributes -->
	<xs:enumeration value="*"/>
	<!-- case not supported by DS, but by partners :Elysium, TSystems, Theorem -->
	<xs:enumeration value="XVL"/>
	<xs:enumeration value="ICAD"/>
	<xs:enumeration value="PRT"/>
	<xs:enumeration value="NX"/>
	<xs:enumeration value="CREO"/>
	<xs:enumeration value="JT"/>
	<xs:enumeration value="x_t"/>
	<xs:enumeration value="x_b"/>
	<xs:enumeration value="authoring"/>   <!-- case where MASTER is not in 3DShape : IFC; SDM new model, ...-->
	<!-- new case , Excite, from 25xGA -->
	<xs:enumeration value="SMGZip"/>
	<!-- fro XCADPostTreatment -->
	<xs:enumeration value="NOConversion"/>
  </xs:restriction>
</xs:simpleType>   
  
  <xs:complexType name="eventType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="eventNameType" name="name" use="required"/>
        <xs:attribute type="eventTypeType" name="type" use="optional"/>
        <xs:attribute type="xs:string" name="maturityGraph" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
 
<!--  list of supported event name -->
<xs:simpleType name="eventNameType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="checkin"/>
    <xs:enumeration value="promote"/>
    <xs:enumeration value="ondemand"/>
    <xs:enumeration value="onXCADSave"/>
  </xs:restriction>
</xs:simpleType> 
  
 <!--  list of supported event type -->
<xs:simpleType name="eventTypeType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Trigger"/>
    <xs:enumeration value="interactiveUpdate"/>
	
  </xs:restriction>
</xs:simpleType>   

  <xs:complexType name="eventsType">
    <xs:sequence>
      <xs:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  
  <!-- each CAD supports a list of data, and a list of event . ultimately, the list of event should be 'independant' from CAD-->
  <xs:complexType name="datasourceType">
    <xs:sequence>
      <xs:element type="sourceType" name="source" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element type="eventsType" name="events" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="dataSourceNameType" name="name" use="required"/>
  </xs:complexType>
  
   <!--  list of supported "CAD" -->
    <xs:simpleType name="dataSourceNameType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="3DEXPERIENCE"/>
        <xs:enumeration value="CATIAV5"/>
        <xs:enumeration value="SOLIDWORKS"/>
        <xs:enumeration value="CREO"/>
        <xs:enumeration value="NX"/>
        <xs:enumeration value="INVENTOR"/>
        <xs:enumeration value="SOLIDEDGE"/>
        <xs:enumeration value="AUTOCAD"/>
        <xs:enumeration value="DRAFTSIGHT"/>
        <!-- CAD supported by Elysium -->
        <xs:enumeration value="ICAD"/>
        <!-- OC only from 22XFD01 -->
        <xs:enumeration value="MicrosoftOffice"/>
        <!-- OC only, from 24XFD01 -->
        <xs:enumeration value="LibreOffice"/>
        <!-- and now ECAD, from 22XFD04 -->
        <xs:enumeration value="CADENCEALLEGRO"/>
        <xs:enumeration value="ALTIUM"/>
        <xs:enumeration value="CADENCEPULSE"/>
        <xs:enumeration value="ZUKENDSCR"/>
        <xs:enumeration value="XPEDITIONEDM"/>
        <!-- GEOVIA, from 23XFD01 -->
        <xs:enumeration value="SURPAC"/>
        <!-- Image, from 23XFD02 -->
        <xs:enumeration value="Image"/>
		<!-- REVIT, from 23xFD01 -->
        <xs:enumeration value="REVIT"/>
        <!-- SIMULALIEN, from 22xFD07 to test ALF Conversion through CAA Converters -->
        <xs:enumeration value="SIMULALIEN"/>
      </xs:restriction>
    </xs:simpleType> 

  
  <!-- each converter may manage different CAD -->
  <xs:complexType name="datasourcesType">
    <xs:sequence>
      <xs:element type="datasourceType" name="datasource" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  
  <!-- Converter : use different files for different converters, they are then agregated-->
  <xs:complexType name="converterType">
    <xs:sequence>
      <xs:element type="datasourcesType" name="datasources" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="converterNameType" name="name" use="required"/>
    <xs:attribute type="xs:string" name="nlsFile" use="required"/>
    <xs:attribute type="xs:boolean" name="synchronous" use="required"/>
    <xs:attribute type="xs:string" name="comment" use="optional"/>
  </xs:complexType>
 
    <!--  list of supported converterNameType -->
    <xs:simpleType name="converterNameType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="3DEXPERIENCE"/>
        <xs:enumeration value="OfficeDocumentConverter"/>
        <xs:enumeration value="CATIAV5"/>
        <xs:enumeration value="SOLIDWORKS"/>
        <xs:enumeration value="CREO"/>
        <xs:enumeration value="NX"/>
        <xs:enumeration value="Inventor"/>
        <xs:enumeration value="SolidEdge"/>
        <xs:enumeration value="AutoCAD"/>
        <xs:enumeration value="ALTIUM"/>
        <xs:enumeration value="CADENCEALLEGRO"/>
        <xs:enumeration value="Elysium"/>
        <xs:enumeration value="3DS"/>
        <xs:enumeration value="XCADPLMBatch"/>
        <xs:enumeration value="XPEDITIONEDM"/>
        <xs:enumeration value="ZUKENDSCR"/>
        <xs:enumeration value="CADENCEPULSE"/>
        <xs:enumeration value="SLW"/>
     </xs:restriction>
    </xs:simpleType> 

 
  <!-- root level of dDerivedouputDeclarative*.xml files -->
  <xs:complexType name="derivedformatmanagementType">
    <xs:sequence>
      <xs:element type="converterType" name="converter" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="derivedformatmanagement" type="derivedformatmanagementType"/>
  
</xs:schema>

=== calmnature/practice3dspace/3dspace/WEB-INF/resources/DerivedOutput/DerivedFormatDeclarative_DassaultSystemes.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!-- 25x version -->
<derivedformatmanagement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DerivedFormatDeclarative.xsd">
	<converter name="3DEXPERIENCE" synchronous="false" nlsFile="emxDerivedFormatManagementStringResource" comment="all the conversion managed asynchronously by DS, By DerivedFormatConverter (OnTheEdge DO converter) or Conversion Service" >
		<datasources>
			<!-- =============================== Native 3DSEXPERIENCE==============================================================================  -->
			<datasource name="3DEXPERIENCE">
				<source name="CATPart" type = "Part">
					<target name="XCADPivot" inputStreamId="authoring" outputStreamId="XCADPivot" downloadable="false" conversionService="true"/>
					<!-- For Step_Pivot, all parameters are hardcoded -->
					<target name="STEP" inputStreamId="authoring" outputStreamId="*" downloadable="true" conversionService="true">
						<!-- STEP Parameters are coming from CATSettings on Converter Machine - Default Level AP242   * Add AP242 Ed4 from 26xFD01 -->						
						<parameter name="ApplicationProtocol" values="AP203|AP203E2|AP214|AP214E3|AP242E1|AP242E2|AP242E3|AP242E4"  type="enum" default="AP242E1" description="Specifies the STEP format into which the data will be exported as explained in Dealing with STEP Data" mandatory="true"/>
						<parameter name="3DAnnotations" values="none|graphic|authoring" type="enum" default="none" description="with PMI. 'authoring' value requires role" />
						<parameter name="Composites" 			values="true|false" type="enum" default="false" 	description="At least one Composites Design app required" />
						<parameter name="UserDefinedAttributes" values="true|false" type="enum" default="false" 	description="" />
						<parameter name="ValidationProperties"  values="true|false" type="enum" default="false" 	description="" />
						<!--  new STEP parameters from 25xFD03 -->
						<parameter name="Groups"  				values="true|false" type="enum" default="false" 	description="" />
						<parameter name="Units"  				values="mm|inch" 	type="enum" default="mm" 		description="units : metric or imperial" />
						<parameter name="GeometricalSets"  		values="true|false" type="enum" default="false" 	description="" />
						<parameter name="ExactGeometry"  		values="exact|tessellated|both" type="enum" default="exact" description="" />
						<parameter name="ExportAlsoEdges"  		values="true|false" type="enum" default="false" 	description="" />
						<parameter name="ExportAlsoNoShowEntities"  values="true|false" type="enum" default="false" 	description="" />
						<parameter name="ExportAlsoNonVisualizedLayers"  values="true|false" type="enum" default="false" 	description="" />
					</target>
					<!-- BELOW MUST be target name=CATPart...but impact to manage   can use conv Service from 23xFD03-->
					<target name="ExactGeometry" inputStreamId="authoring" outputStreamId="catiav5"  downloadable="false" conversionService="true">
					<!-- By default - ExactGeometry CXR25 CATPart AsResult this one is for PowerBy CATIAV5 
					           but one may prefer >=CXR31 to get associativiy (means a downward cATPart with stableId, allowinf rerouteLinks -->
						<parameter name="AdditionalFeatures"  values="GenericFeature" type="enum" default="GenericFeature" description="adjust the CATIA V5 level according to the needed features" />
					</target>
					<!-- CATPart for exchange from 23xFD04    from 24XBeta2, we also support DFC/OP case -->  
					<target name="CATPart" inputStreamId="authoring" outputStreamId="*"  downloadable="true"  conversionService="true" >
						<parameter name="level"  values="CATIAV5R18|CATIAV5R19|CATIAV5R20|CATIAV5R21|CATIAV5R22|CATIAV5R23|CATIAV5R24|CATIAV5R25|CATIAV5R26|CATIAV5R27|CATIAV5R28|CATIAV5R29|CATIAV5R30|CATIAV5R31|CATIAV5R32|CATIAV5R33|CATIAV5R34|CATIAV5R35|CATIAV5R36" type="enum" default="CATIAV5R31" description="the CATIA V5 level" mandatory="true" />
					</target>					

					<!-- V5 CGR DO from 24xFD04    conversion Native 3DEXP to V5 CGR (as a DO, without changing authoringVisu! --> 
					<target name="CGR" inputStreamId="authoringvisu" outputStreamId="cgrv5" downloadable="false" conversionService="true">
                    <!-- hardcoded parameter "V5Version"="CGRR19"
					 	<parameter name="CGR_Version" values="R19" type="enum" default="R19" mandatory="true" description="force V5 CGR (aka CGRR19)"/>  -->
					  <!-- parameter name="NO_WIREFRAME" values="true|false" type="enum" default="false" description="" / -->
					</target>
										
					
					<target name="PDF" inputStreamId="authoring" outputStreamId="PDF" downloadable="true" conversionService="true"/>
					<!-- For Conversion of CATPart with 2DLayout feature - No parameters required for Conversion  managed by CO from 25xFD01, -->
					<target name="ACIS" inputStreamId="authoring" outputStreamId="acis_powerby" downloadable="false" conversionService="true">
					    <!-- ACIS version is no longer a parameter for 'internal DS format', it s hard coded as version=26-->
					</target>
					<!-- New from 23xFD01 : 3DEXP to SDM (GEOVIA SURPAC) (and forward to CO from 23xFD02)  PowerBy format -->
					<target name="SurpacSDM" inputStreamId="authoring" outputStreamId="SurpacSDM" downloadable="false" conversionService="true">
						<parameter name="Extension" values="sdm" type="enum" default="sdm" description="" mandatory="true"/>
						<parameter name="StreamFormat" values="SurpacSDM" type="enum" default="SurpacSDM" description="" mandatory="true"/>
						<!-- add new parameters in 25xFD02 -->
						<parameter name="exportKnowledgeParameter" values="All|None" type="enum" default="All" description="Allows you to export the knowledge parameter of a feature as metadata" mandatory="true"/>
						<parameter name="exportSurpacObjectMode" values="GeometricalSet|GeometricalFeature" type="enum" default="GeometricalFeature" description="Allows you to export a single String or TriObject to group all the geometrical features aggregated under the same Geometrical Set. When it is not selected, each geometrical feature is exported in a separated String or triObject." mandatory="true"/>
						<parameter name="exportMagnitudeLength" values="Millimeter|Meter|Kilometer|Inch|Foot|Yard|Mile" type="enum" default="Meter" description="select a specific unit for export of Length magnitude." mandatory="true"/>
						<!-- add new parameters in 26xFD02 -->
						<parameter name="ExportOnlyShownEntities"  values="true|false" type="enum" default="true" 	description="" />
					</target>
					<!-- to come in some 26X late FD 
					<target name="OMF" inputStreamId="authoring" outputStreamId="OMF" downloadable="true" conversionService="true">
						<parameter name="Extension" values="sdm" type="enum" default="sdm" description="" mandatory="true"/>
					</target>
					-->
					
		            <!-- Need to add XCV   for 23XFD01 -->			
					<target name="xcvcore_zip" inputStreamId="authoring" outputStreamId="XCV" downloadable="false" conversionService="true" cloudOnly="true" >
						<parameter name="XCV_TRACE_LEVEL" values="NONE|LOW|MEDIUM|HIGH"  type="enum" default="NONE" description="traces level for the conversion"/>
						<parameter name="optimisedBoundingBox" values="true|false" type="enum" default="false" description="Smallest parallelepiped volume that contains the part"/>
					</target>
				</source>
				
				<source name="CATDrawing" type = "Drawing">
					<target name="PDF" inputStreamId="authoring" outputStreamId="*" downloadable="true" conversionService="true">
						<!-- PDF Parameters are coming from CATSettings on Converter Machine -->
						<!-- PDF parameters from 22xFD03 -->
						<parameter name="MultiSheetMode"    values="CURRENT|ALLIN1|ALLCURRENT1st" type="enum" default="CURRENT"  description="Define what sheets will the PDF includes" />
						<!-- NOT READY IN 22XFD03, reactivated in FD04 --> 
						<parameter name="ExcludeDetailSheet"   values="true|false"               type="enum" default="false"    description="Exclude the details sheets of the drawing in the PDF" />
						<parameter name="ColorMode"            values="RGB|GREYSCALE|MONO"       type="enum" default="RGB"      description="Color mode" />
						<parameter name="TextBlanking"         values="true|false"               type="enum" default="false"    description="Display the text blanking" />
						<parameter name="WhiteVectorsInBlack"  values="true|false"               type="enum" default="true"     description="Change the white vector in black to be seen on white background" />
						<!-- same as for STEP, the below mand param allows to compute the 'unified format (refinement from 'PDF'  -->
						<parameter name="PDFSaveMode"          values="PDF_1_3|PDF_A_1b|PDF_1_6" type="enum" default="PDF_1_3"  description="PDF version to use" mandatory="true"/>
					</target>

					<!-- new from 26xFD02 ...alternate generation from UDL in authoringVisu -->
					<target name="PDF" inputStreamId="authoringvisu" outputStreamId="*" downloadable="true" conversionService="true">
						<parameter name="MultiSheetMode"    values="CURRENT|ALLIN1|ALLCURRENT1st" type="enum" default="CURRENT"  description="Define what sheets will the PDF includes" />
						<parameter name="ExcludeDetailSheet"   values="true|false"               type="enum" default="false"    description="Exclude the details sheets of the drawing in the PDF" />
						<parameter name="ColorMode"            values="RGB|GREYSCALE|MONO"       type="enum" default="RGB"      description="Color mode" />
						<parameter name="TextBlanking"         values="true|false"               type="enum" default="false"    description="Display the text blanking" />
						<parameter name="WhiteVectorsInBlack"  values="true|false"               type="enum" default="true"     description="Change the white vector in black to be seen on white background" />
